eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service-zuul
feign:
  hystrix:
    # Feign是自带断路器
    enabled: true